# Generated by Django 3.2.4 on 2021-08-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analy', '0002_imzacadq1bk_imzacadq2bk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imzacadq1bk',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='imzacadq2bk',
            options={'managed': False},
        ),
    ]
